//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgm_decoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cgm_struct {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cgm_struct() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cgm_decoder.cgm_struct", typeof(cgm_struct).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,	0	,	no-op
        ///0,	1	,	BEGIN METAFILE
        ///0,	2	,	END METAFILE
        ///0,	3	,	BEGIN PICTURE
        ///0,	4	,	BEGIN PICTURE BODY
        ///0,	5	,	END PICTURE
        ///0,	6	,	BEGIN SEGMENT
        ///0,	7	,	END SEGMENT
        ///0,	8	,	BEGIN FIGURE
        ///0,	9	,	END FIGURE
        ///0,	13	,	BEGIN PROTECTION REGION
        ///0,	14	,	END PROTECTION REGION
        ///0,	15	,	BEGIN COMPOUND LINE
        ///0,	16	,	END COMPOUND LINE
        ///0,	17	,	BEGIN COMPOUND TEXT PATH
        ///0,	18	,	END COMPOUND TEXT PATH
        ///0,	19	,	BEGIN TILE ARRAY
        ///0,	20	,	END TILE ARRAY
        ///0,	21	,	BEGIN APPLICATION STRUCTURE
        ///0,	22	,	BEGIN APPLICATION STRU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cgm_element_names {
            get {
                return ResourceManager.GetString("cgm_element_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hashtype_1 {
            get {
                object obj = ResourceManager.GetObject("hashtype_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hashtype_2 {
            get {
                object obj = ResourceManager.GetObject("hashtype_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hashtype_3 {
            get {
                object obj = ResourceManager.GetObject("hashtype_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hashtype_4 {
            get {
                object obj = ResourceManager.GetObject("hashtype_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hashtype_5 {
            get {
                object obj = ResourceManager.GetObject("hashtype_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hashtype_6 {
            get {
                object obj = ResourceManager.GetObject("hashtype_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
